@startuml Request project settings from all services

title Request project settings from all services


actor User as usr
participant WebService as wp

box Rabbit #LightSkyBlue 
    queue "CentralHub" as CentralHub #LightBlue
    queue "MainBot\nqueue" as mbQueue #BlueViolet
    queue "Jenkins\nqueue" as jenkinsQueue #BlueViolet
    queue "Redmine\nqueue" as redmineQueue #BlueViolet
end box

participant "MainBot\nservice" as mb
participant "Jenkins\nservice" as jenkins
participant "Redmine\nservice" as redmine


usr -> wp : Edit\nsingle project\nsettings page
activate wp
wp -> mbQueue : Direct request\nproject information
mbQueue -> mb  : Consume message
mb --> mbQueue : Main information about project
mbQueue --> wp : Main information\nabout project

wp -> CentralHub : Request any settings
activate CentralHub

wp --> usr : [WebPage] \n Main project information
deactivate wp

CentralHub -> jenkinsQueue : Publish requested infromation
activate jenkinsQueue
CentralHub -> redmineQueue : Publish requested infromation
deactivate CentralHub

activate redmineQueue
...
jenkinsQueue -> jenkins : Consume request\nproject settings message 
activate jenkins
deactivate jenkinsQueue
redmineQueue -> redmine : Consume request\nproject settings message 
activate redmine
deactivate redmineQueue
...
jenkins -> jenkins : Load or generate\n jenkins settings \n for project
jenkins -> CentralHub : Project settings\nfor jenkins service
deactivate jenkins
activate CentralHub
...
CentralHub -> wp : Consume settings message
deactivate CentralHub
activate wp
wp -> wp : Change webpage data
wp -> wp : [Blazor tree]
wp --> usr : [UpdatedWebPage via SignalR] \n Main project information\n + Jenkins settings for project
deactivate wp

... other services ...
hnote across #LightSteelBlue: Other services are handled in the same way 
redmine -> redmine : Load or generate\n redmine settings \n for project
redmine -> CentralHub : Project settings\nfor redmine service
deactivate redmine
activate CentralHub
...
CentralHub -> wp : Consume settings message
deactivate CentralHub
activate wp
wp -> wp : Change webpage data
wp -> wp : [Blazor tree]
wp --> usr : [UpdatedWebPage via SignalR] \n Main project information\n + Jenkins settings for project\n + Redmine settings for project
deactivate wp

== End of generating project settings page == 

...
note over usr, wp : \n <size:22>**User changing settings**</size> \n

@enduml